### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by concerned-user** [tux3/qTox#1023] opened 2015-01-19 18:30 UTC
I don't know if this is the correct place to ask this, but I don't know what other ways to contact you and this is a very serious issue with the Tox project. irungentoo deleted these concerns from the toxcore repository, so this I have to bring it up here instead. irungentoo is enforcing censorship on this.

Recently @Proplex left the project over the following discussion: https://gist.github.com/irungentoo/5af26f5edefcdb7eac72

Soon after, I came to the following intriguing link: https://mail.tox.im/prolapse.txt

Can you explain why the Tox Foundation is tracking when Proplex visits your websites?
For an organization that says it is privacy-respecting, freedom lover and whatnot, this is highly contradictory and raise many concerns.

PS: sorry if this isn't the right repository, but this issue really needs to be discussed and it is relevant to the Tox project as a whole.

EDIT:
**Red alert:** The document of https://mail.tox.im/prolapse.txt has been edited. Really looks like someone from the Tox Foundation is trying to cover this up. Hopefully the service archive.today let us see what was previously hosted on the website.
https://archive.today/KkSWp

**Comment by concerned-user** [comment] 2015-01-19 20:05
https://gist.github.com/urras/ba792274f5aaf662a082

**Comment by ProMcTagonist** [comment] 2015-01-19 23:43
I was wondering where Proplex went. He was the only one who could calm things down when Stq and irungentoo were fighting more than usual.

>https://gist.github.com/urras/ba792274f5aaf662a082

That's completely unacceptable.

The issue is still on toxcore, he just closed it. https://github.com/irungentoo/toxcore/issues/1228

**Comment by dubslow** [comment] 2015-01-20 00:04
This is utterly not the place for this. However, irungentoo has just said he doesn't really care about the server logs, so for now, this issue is remaining unedited, but closed and locked.

**Closed by dubslow** 2015-01-20 00:04 UTC
